### ISSUE TITLE
Hacktober Feature Request: Create Pride Logo

### ISSUE THREAD

**Issue by wordshaker** [dotnetnotts/dotnetnotts-web#32]
### Describe the feature

- Create a Pride themed logo for .NET Notts

### Advantages

- Helps us celebrate and support Pride next year

#### Acceptance Criteria

Functional and non-functional criteria that should be met by this work

- [ ] Logo is designed and added into an assets folder

**Comment by jenniferpinai** [comment]
Is the Pride theme logo in accordance with the current .NET Notts branding (e.g. change the green palette background to rainbow theme)? The assets folder currently has the logo in .png format—do you happen to have an editable, vector format of it? This will help instead of recreating the logo entirely.

**Comment by wordshaker** [comment]
Hi @jenniferpinai 

- Change the pallette to a rainbow theme
- I can try to create a more editable version of it but I'm limited by my use of Gimp. I will ask one of my designer friends if she can create an editable, vector format of it

**Comment by wordshaker** [comment]
Here's an SVG of the logo if it helps: https://drive.google.com/file/d/1D-3XEXN96a2Iak_5fQ7vk4jTHZlg_9Bb/view?usp=sharing

**Comment by kavita121** [comment]
Heyy!! Can I work on this??

**Comment by wordshaker** [comment]
@kavita121 yes you can 😄 get in touch if you have any questions
